/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiGenerateRouteImport } from './routes/api.generate'
import { Route as ApiLinkedinStartRouteImport } from './routes/api.linkedin.start'
import { Route as ApiLinkedinPublishRouteImport } from './routes/api.linkedin.publish'
import { Route as ApiLinkedinDisconnectRouteImport } from './routes/api.linkedin.disconnect'
import { Route as ApiLinkedinCallbackRouteImport } from './routes/api.linkedin.callback'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinStartRoute = ApiLinkedinStartRouteImport.update({
  id: '/api/linkedin/start',
  path: '/api/linkedin/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinPublishRoute = ApiLinkedinPublishRouteImport.update({
  id: '/api/linkedin/publish',
  path: '/api/linkedin/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinDisconnectRoute = ApiLinkedinDisconnectRouteImport.update({
  id: '/api/linkedin/disconnect',
  path: '/api/linkedin/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLinkedinCallbackRoute = ApiLinkedinCallbackRouteImport.update({
  id: '/api/linkedin/callback',
  path: '/api/linkedin/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
  '/api/linkedin/disconnect': typeof ApiLinkedinDisconnectRoute
  '/api/linkedin/publish': typeof ApiLinkedinPublishRoute
  '/api/linkedin/start': typeof ApiLinkedinStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
  '/api/linkedin/disconnect': typeof ApiLinkedinDisconnectRoute
  '/api/linkedin/publish': typeof ApiLinkedinPublishRoute
  '/api/linkedin/start': typeof ApiLinkedinStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRoute
  '/login': typeof LoginRoute
  '/methodology': typeof MethodologyRoute
  '/pricing': typeof PricingRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/linkedin/callback': typeof ApiLinkedinCallbackRoute
  '/api/linkedin/disconnect': typeof ApiLinkedinDisconnectRoute
  '/api/linkedin/publish': typeof ApiLinkedinPublishRoute
  '/api/linkedin/start': typeof ApiLinkedinStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/methodology'
    | '/pricing'
    | '/api/generate'
    | '/api/linkedin/callback'
    | '/api/linkedin/disconnect'
    | '/api/linkedin/publish'
    | '/api/linkedin/start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/methodology'
    | '/pricing'
    | '/api/generate'
    | '/api/linkedin/callback'
    | '/api/linkedin/disconnect'
    | '/api/linkedin/publish'
    | '/api/linkedin/start'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/methodology'
    | '/pricing'
    | '/api/generate'
    | '/api/linkedin/callback'
    | '/api/linkedin/disconnect'
    | '/api/linkedin/publish'
    | '/api/linkedin/start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRoute
  LoginRoute: typeof LoginRoute
  MethodologyRoute: typeof MethodologyRoute
  PricingRoute: typeof PricingRoute
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiLinkedinCallbackRoute: typeof ApiLinkedinCallbackRoute
  ApiLinkedinDisconnectRoute: typeof ApiLinkedinDisconnectRoute
  ApiLinkedinPublishRoute: typeof ApiLinkedinPublishRoute
  ApiLinkedinStartRoute: typeof ApiLinkedinStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/start': {
      id: '/api/linkedin/start'
      path: '/api/linkedin/start'
      fullPath: '/api/linkedin/start'
      preLoaderRoute: typeof ApiLinkedinStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/publish': {
      id: '/api/linkedin/publish'
      path: '/api/linkedin/publish'
      fullPath: '/api/linkedin/publish'
      preLoaderRoute: typeof ApiLinkedinPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/disconnect': {
      id: '/api/linkedin/disconnect'
      path: '/api/linkedin/disconnect'
      fullPath: '/api/linkedin/disconnect'
      preLoaderRoute: typeof ApiLinkedinDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/linkedin/callback': {
      id: '/api/linkedin/callback'
      path: '/api/linkedin/callback'
      fullPath: '/api/linkedin/callback'
      preLoaderRoute: typeof ApiLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRoute,
  LoginRoute: LoginRoute,
  MethodologyRoute: MethodologyRoute,
  PricingRoute: PricingRoute,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiLinkedinCallbackRoute: ApiLinkedinCallbackRoute,
  ApiLinkedinDisconnectRoute: ApiLinkedinDisconnectRoute,
  ApiLinkedinPublishRoute: ApiLinkedinPublishRoute,
  ApiLinkedinStartRoute: ApiLinkedinStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
